#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

cd "$(dirname "$0")/.."

echo "Running static type checking with mypy..."
python3 -m mypy \
    custom_components/xplora_watch/ \
    --exclude 'custom_components/xplora_watch/geocoder\.py'

echo "Type checking completed!"